[window]
decorations = "None"
opacity = 0.9
startup_mode = "Maximized"

[colors.bright]
black = "0x4d4d4d"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "0x14151b"
blue = "0x4d5b86"
cyan = "0x59dffc"
green = "0x1ef956"
magenta = "0xff46b0"
red = "0xff2222"
white = "0xe6e6d1"
yellow = "0xebf85b"

[colors.footer_bar]
background = "0x282a36"
foreground = "0xf8f8f2"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[colors.search.focused_match]
background = "0xffb86c"
foreground = "0x44475a"

[colors.search.matches]
background = "0x50fa7b"
foreground = "0x44475a"

[colors.selection]
background = "0x44475a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
chars = "\u001bj"

[[keyboard.bindings]]
key = "J"
mods = "Alt|Shift"
chars = "\u001bJ"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "\u001bk"

[[keyboard.bindings]]
key = "K"
mods = "Alt|Shift"
chars = "\u001bK"

[[keyboard.bindings]]
key = "H"
mods = "Alt"
chars = "\u001bh"

[[keyboard.bindings]]
key = "H"
mods = "Alt|Shift"
chars = "\u001bH"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
chars = "\u001bl"

[[keyboard.bindings]]
key = "L"
mods = "Alt|Shift"
chars = "\u001bL"

[[keyboard.bindings]]
key = "M"
mods = "Alt"
chars = "\u001bm"

[[keyboard.bindings]]
key = "Y"
mods = "Alt"
chars = "\u001by"

[[keyboard.bindings]]
key = "P"
mods = "Alt"
chars = "\u001bp"
